unstable_features = true
edition = "2024"
style_edition = "2024"
fn_params_layout = "Tall"
trailing_comma = "Vertical"
match_block_trailing_comma = true
imports_granularity = "Crate"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
newline_style = "Unix"
use_small_heuristics = "Max"
hex_literal_case = "Lower"